server:
  port: 8282
  servlet:
    session:
      cookie:
        name: PSESSION
security:
  oauth2:
    client:
      client-id: portal
      client-secret: 12345
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
logging:
  level:
    org:
      hibernate:
        type: DEBUG
        
resource-service: http://localhost:8181